#!/bin/sh
# Ensure we use the same Node version as launchd (nvm default)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

npm run build
npm rebuild better-sqlite3 2>/dev/null
launchctl kickstart -k gui/$(id -u)/com.nanoclaw
